In [41]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import locale
import matplotlib.dates as mdates
import matplotlib.patches as mpatches

##### Google Ads

In [42]:
#Set locale to Spanish
locale.setlocale(locale.LC_TIME, 'es_ES.UTF-8')

google_ads = pd.read_csv('/Users/cesarchaparro/Desktop/GitHub/Chapoteos/analytics_data/analytics/14-27.04.2025/csv/google_ads.csv', encoding='utf-8')
# Convert 'Día' to datetime, handling potential errors
google_ads['Día'] = pd.to_datetime(google_ads['Día'], errors='coerce')
# Convert 'Impr.' to integer
google_ads['Impr.'] = google_ads['Impr.'].astype('int64')
# Convert CTR to floatin and delete the % symbol
google_ads['CTR'] = google_ads['CTR'].str.replace(',', '', regex=False).str.rstrip('%').astype(float).div(100)
# Convert 'Coste' to float
google_ads['Coste'] = google_ads['Coste'].str.replace(',', '', regex=False).astype(float)
# Convert 'Conversiones' to integer
google_ads['Conversiones']  = google_ads['Conversiones'].str.replace(',', '', regex=False).astype('int64')
# Convert 'Ingresos' to float
google_ads['Ingresos'] = google_ads['Ingresos'].str.replace(',', '', regex=False).astype(float)
google_ads.head()

,Campaña,Objetivos de conversión,Día,Dispositivo,Clics,Impr.,CTR,Código de moneda,Coste,Conversiones,Interacciones,Ingresos,Resultados
0,Búsqueda | General,"[PHONE_CALL_LEAD/CALL_FROM_ADS, PURCHASE/WEBSI...",2025-04-27,Equipos informáticos,1,12,8.33,EUR,30.0,0,1,0.0,0
1,Búsqueda | General,"[PHONE_CALL_LEAD/CALL_FROM_ADS, PURCHASE/WEBSI...",2025-04-27,Teléfonos móviles,54,482,11.20,EUR,3065.0,0,54,0.0,"Cómo llegar: 1,00"
2,Búsqueda | General,"[PHONE_CALL_LEAD/CALL_FROM_ADS, PURCHASE/WEBSI...",2025-04-27,Tablets,0,2,0.00,EUR,0.0,0,0,0.0,0
3,Pmax | Promoción Bonos - MOFU,"[CONTACT/GOOGLE_HOSTED, GET_DIRECTIONS/GOOGLE_...",2025-04-27,Equipos informáticos,0,261,0.00,EUR,0.0,0,0,0.0,0
4,Pmax | Promoción Bonos - MOFU,"[CONTACT/GOOGLE_HOSTED, GET_DIRECTIONS/GOOGLE_...",2025-04-27,Teléfonos móviles,5,1,0.38,EUR,60.0,0,6,0.0,"Interacción: 14,00"

In [43]:
google_ads.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 184 entries, 0 to 183
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Campaña                  184 non-null    object
 1   Objetivos de conversión  184 non-null    object
 2   Día                      184 non-null    datetime64[ns]
 3   Dispositivo              184 non-null    object
 4   Clics                    184 non-null    int64
 5   Impr.                    184 non-null    int64
 6   CTR                      184 non-null    float64
 7   Código de moneda         184 non-null    object
 8   Coste                    184 non-null    float64
 9   Conversiones             184 non-null    int64
 10  Interacciones            184 non-null    int64
 11  Ingresos                 184 non-null    float64
 12  Resultados               184 non-null    object
dtypes: datetime64[ns](1), float64(3), int64(4), object(5)
memory usage: 18.8+ KB

In [44]:
#Set locale to Spanish
locale.setlocale(locale.LC_TIME, 'es_ES.UTF-8')

google_ads_conversions = pd.read_csv('/Users/cesarchaparro/Desktop/GitHub/Chapoteos/analytics_data/analytics/14-27.04.2025/csv/google_ads_conversions.csv', encoding='utf-8')
# Convert 'Día' to datetime, handling potential errors
google_ads_conversions['Día'] = pd.to_datetime(google_ads_conversions['Día'], errors='coerce')
google_ads_conversions.head()

,Día,Fuente de conversiones,Categoría de conversión,Acción de conversión,Campaña,Conversiones
0,2025-04-26,Sitio web,Envío de formulario para clientes potenciales,Formulario Pag Gracias- Nat Adultos,Búsqueda | General,2
1,2025-04-26,Sitio web,Envío de formulario para clientes potenciales,Formulario- Pa Gracias Matronatación,Búsqueda | General,2
2,2025-04-26,Sitio web,Envío de formulario para clientes potenciales,Formulario- Pag Gracias Nat Infantil,Búsqueda | General,2
3,2025-04-26,En páginas alojadas en Google,Cómo llegar,Acciones locales: clic en Cómo llegar,Pmax | Promoción Bonos - RMK,1
4,2025-04-24,Sitio web,Envío de formulario para clientes potenciales,Formulario Pag Gracias- Nat Adultos,Búsqueda | General,1

In [45]:
google_ads_conversions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Día                      30 non-null     datetime64[ns]
 1   Fuente de conversiones   30 non-null     object
 2   Categoría de conversión  30 non-null     object
 3   Acción de conversión     30 non-null     object
 4   Campaña                  30 non-null     object
 5   Conversiones             30 non-null     int64
dtypes: datetime64[ns](1), int64(1), object(4)
memory usage: 1.5+ KB

***

##### Meta

In [50]:
# Set locale to Spanish
locale.setlocale(locale.LC_TIME, 'es_ES.UTF-8')

# Read the file and skip the first row with NaN values
meta = pd.read_csv(
    '/Users/cesarchaparro/Desktop/GitHub/Chapoteos/analytics_data/analytics/14-27.04.2025/csv/meta.csv',
    encoding='utf-8'
)

# Display the result
meta.head()

,Campaign name,Day,Platform,Objective,Result type,Results,Reach,Impressions,Amount spent (EUR),Views,...,CPC (all),CTR (all),Page engagement,Facebook follows or likes,Link clicks,Instagram profile visits,Website leads,Objective.1,Website purchases conversion value,Estimated ad recall lift (people)
0,promoción post Chapoteos MATRO,All,All,All,Link clicks,661.0,23833,31489,51.91,29593,...,0.051703,3.188415,706.0,NaN,661.0,7,NaN,LINK_CLICKS,NaN,0
1,promoción post Chapoteos MATRO,2025-04-14,All,All,Link clicks,58.0,2101,2275,4.16,2117,...,0.064000,2.857143,58.0,NaN,58.0,0,NaN,LINK_CLICKS,NaN,0
2,promoción post Chapoteos MATRO,2025-04-14,instagram,All,Link clicks,43.0,1172,1264,3.23,1264,...,0.075116,3.401899,43.0,NaN,43.0,0,NaN,LINK_CLICKS,NaN,0
3,promoción post Chapoteos MATRO,2025-04-14,instagram,LINK_CLICKS,Link clicks,43.0,1172,1264,3.23,1264,...,0.075116,3.401899,43.0,NaN,43.0,0,NaN,LINK_CLICKS,NaN,0
4,promoción post Chapoteos MATRO,2025-04-14,facebook,All,Link clicks,13.0,822,853,0.86,853,...,0.043000,2.344666,13.0,NaN,13.0,0,NaN,LINK_CLICKS,NaN,0

In [52]:
meta.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 684 entries, 0 to 683
Data columns (total 21 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Campaign name                       684 non-null    object
 1   Day                                 684 non-null    object
 2   Platform                            684 non-null    object
 3   Objective                           684 non-null    object
 4   Result type                         327 non-null    object
 5   Results                             327 non-null    float64
 6   Reach                               684 non-null    int64
 7   Impressions                         684 non-null    int64
 8   Amount spent (EUR)                  684 non-null    float64
 9   Views                               684 non-null    int64
 10  Clicks (all)                        684 non-null    int64
 11  CPC (all)                           540 non-null    float64
 12  CTR (all)                           680 non-null    float64
 13  Page engagement                     578 non-null    float64
 14  Facebook follows or likes           60 non-null     float64
 15  Link clicks                         504 non-null    float64
 16  Instagram profile visits            684 non-null    int64
 17  Website leads                       135 non-null    float64
 18  Objective.1                         684 non-null    object
 19  Website purchases conversion value  4 non-null      float64
 20  Estimated ad recall lift (people)   684 non-null    int64
dtypes: float64(9), int64(6), object(6)
memory usage: 112.3+ KB

***

##### Google Analytics

In [49]:
#Set locale to Spanish
locale.setlocale(locale.LC_TIME, 'es_ES.UTF-8')

google_analytics_session_manual_source = pd.read_csv('/Users/cesarchaparro/Desktop/GitHub/Chapoteos/analytics_data/analytics/14-27.04.2025/csv/google_analytics_session_manual_source.csv', encoding='utf-8')
google_analytics_session_manual_source.head()

,Session manual source,Date,Active users,Sessions,Engaged sessions,Average engagement time per session,Engaged sessions per active user,Events per session,Engagement rate,Key events,Event count,Total revenue
0,ig,20250414,122,125,50,11.936000,0.409836,4.728000,0.400000,0,591,0
1,ig,20250423,107,121,56,11.471074,0.523364,5.049587,0.462810,0,611,0
2,ig,20250422,112,120,57,14.325000,0.508929,5.233333,0.475000,0,628,0
3,google,20250422,103,119,103,52.647059,1.000000,9.857143,0.865546,0,1173,0
4,google,20250427,93,109,88,41.798165,0.946237,10.146789,0.807339,0,1106,0